return {
  'akinsho/bufferline.nvim',
  version = '*',
  event = 'VeryLazy',
  dependencies = {
    'nvim-tree/nvim-web-devicons',
    'echasnovski/mini.bufremove',
  },
  keys = {
    { '<Space>b1', '<cmd>BufferLineGoToBuffer 1<CR>' },
    { '<Space>b2', '<cmd>BufferLineGoToBuffer 2<CR>' },
    { '<Space>b3', '<cmd>BufferLineGoToBuffer 3<CR>' },
    { '<Space>b4', '<cmd>BufferLineGoToBuffer 4<CR>' },
    { '<Space>b5', '<cmd>BufferLineGoToBuffer 5<CR>' },
    { '<Space>b6', '<cmd>BufferLineGoToBuffer 6<CR>' },
    { '<Space>b7', '<cmd>BufferLineGoToBuffer 7<CR>' },
    { '<Space>b8', '<cmd>BufferLineGoToBuffer 8<CR>' },
    { '<Space>b9', '<cmd>BufferLineGoToBuffer 9<CR>' },
    { '<Leader>bb', '<cmd>BufferLineMovePrev<CR>', desc = 'Move back' },
    { '<Leader>bl', '<cmd>BufferLineCloseLeft<CR>', desc = 'Close Left' },
    { '<Leader>br', '<cmd>BufferLineCloseRight<CR>', desc = 'Close Right' },
    { '<Leader>bn', '<cmd>BufferLineMoveNext<CR>', desc = 'Move next' },
    { '<Leader>bp', '<cmd>BufferLinePick<CR>', desc = 'Pick Buffer' },
    { '<Leader>bP', '<cmd>BufferLineTogglePin<CR>', desc = 'Pin/Unpin Buffer' },
    { '<Leader>bsd', '<cmd>BufferLineSortByDirectory<CR>', desc = 'Sort by directory' },
    { '<Leader>bse', '<cmd>BufferLineSortByExtension<CR>', desc = 'Sort by extension' },
    { '<Leader>bsr', '<cmd>BufferLineSortByRelativeDirectory<CR>', desc = 'Sort by relative dir' },
  },
}
